using System;
using System.Collections.Generic;

using HUtil.Runtime.Animation;
using HUtil.Runtime.Observable;

using Sirenix.OdinInspector;

using TMPro;

using UnityEngine;

namespace HUtil.UI.Binder
{
    /// <summary>
    /// 동적 애니메이션 클립 생성을 이용한 멀티 바인더
    /// </summary>
    public class OnOffClipBinder : MonoBinder
    {
        [SerializeField, PropertyOrder(100), PropertySpace(SpaceAfter = 10, SpaceBefore = 0)] private GameObject _target;   
        [SerializeField, PropertyOrder(110), HorizontalGroup("OnAnimation")] private AnimationClip _onClip;
        [SerializeField, PropertyOrder(120), HorizontalGroup("OffAnimation")] private AnimationClip _offClip;
        [SerializeField, PropertyOrder(140), PropertySpace(SpaceAfter = 0, SpaceBefore = 10)] 
        private PropertyBindingPort<bool> _isOn_prop = new PropertyBindingPort<bool>(BindingType.OfType(BindingBaseType.Bool), BindingDirectionFlags.ToUI);

        protected override void Reset()
        {
            base.Reset();
            _target = gameObject;
        }
        
        [GUIColor(1, 0.7f, 0.7f)]
        [Button(Name = "Capture", Icon = SdfIconType.Record, DirtyOnClick = true)]
        [HorizontalGroup("OnAnimation", Width = 80), PropertyOrder(111)]
        private void CaptureOnPose(){
            var snapshot = new AnimationSnapshot(_target);
            snapshot.CapturePoseA();
            _onClip = snapshot.CreateAnimationClipA($"On_{_target.name}_{Mathf.Abs(_target.GetInstanceID())}_AutoGenerated");
        }

        [GUIColor(1, 0.7f, 0.7f)]
        [Button(Name = "Capture", Icon = SdfIconType.Record, DirtyOnClick = true)]
        [HorizontalGroup("OffAnimation", Width = 80), PropertyOrder(121)]
        private void CaptureOffPose(){
            var snapshot = new AnimationSnapshot(_target);
            snapshot.CapturePoseB();
            _offClip = snapshot.CreateAnimationClipB($"Off_{_target.name}_{Mathf.Abs(_target.GetInstanceID())}_AutoGenerated");
        }

        [Button(Name = "Preview On", Icon = SdfIconType.Play, DirtyOnClick = true), HorizontalGroup("Preview"), PropertyOrder(130)]
        private void PreviewOn(){
            if(_onClip == null) return;
            _onClip.SampleAnimation(_target, 0);
        }

        [Button(Name = "Preview Off", Icon = SdfIconType.Play, DirtyOnClick = true), HorizontalGroup("Preview"), PropertyOrder(131)]
        private void PreviewOff(){
            if(_offClip == null) return;
            _offClip.SampleAnimation(_target, 0);
        }

        protected void OnValidate()
        {
            _isOn_prop.Validate(this);
        }

        protected override void BindInternal(Dictionary<string, IViewModelProperty> bindMap, CompositeDisposable disposable)
        {
            _isOn_prop.Bind(bindMap, disposable, SetBool);
        }

        private void SetBool(bool value)
        {
            if (value)
            {
                _onClip?.SampleAnimation(_target, 0);
            }
            else
            {
                _offClip?.SampleAnimation(_target, 0);
            }
        }
    }
}