using System;
using System.Collections.Generic;
using System.Linq;

using HUtil.UI;
using HUtil.Runtime.Extension;
using HUtil.UI.Binder;

using UnityEditor;
using UnityEngine;
using HUtil.Editor;
using HUtil.Editor.Animation;

namespace HUtil.UI.Editor
{
    [CustomEditor(typeof(OnOffClipBinder))]
    public class OnOffClipBinderDrawer : UnityEditor.Editor
    {
        private AnimationSnapshot.CaptureOption _captureOption = new AnimationSnapshot.CaptureOption(new Type[0], new Type[] { typeof(MonoBinder) }, new string[0]);

        public override void OnInspectorGUI(){
            serializedObject.Update();

            var propertyBinder = target as OnOffClipBinder;

            var targetProp = serializedObject.FindProperty("_target");
            var onAnimationProp = serializedObject.FindProperty("_onAnimation");
            var offAnimationProp = serializedObject.FindProperty("_offAnimation");
            var boolPropProp = serializedObject.FindProperty("_isOn_prop");

            // # Target
            EditorGUILayout.PropertyField(targetProp, new GUIContent("Target"));

            // # Is On Property
            EditorGUILayout.PropertyField(boolPropProp, new GUIContent("Is On Property"));

            // # On Animation
            EditorGUILayout.PropertyField(onAnimationProp, new GUIContent("On Animation"));
            var rect = EditorGUILayout.GetControlRect();
            if(GUI.Button(rect, "Capture")){
                var _snapshot = new AnimationSnapshot(propertyBinder.gameObject, _captureOption);
                AnimationClip clip = null;
                _snapshot.CapturePoseA();
                clip = _snapshot.CreateAnimationClipA($"On_{propertyBinder.gameObject.name}_{Mathf.Abs(propertyBinder.GetInstanceID())}_AutoGenerated");
                if(onAnimationProp.objectReferenceValue is AnimationClip oldClip && oldClip.name.EndsWith("_AutoGenerated")){
                    AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(oldClip));
                    AssetDatabase.SaveAssets();
                    onAnimationProp.objectReferenceValue = null;
                }
                onAnimationProp.objectReferenceValue = clip;
            }

            // # Off Animation
            EditorGUILayout.PropertyField(offAnimationProp, new GUIContent("Off Animation"));
            rect = EditorGUILayout.GetControlRect();
            if(GUI.Button(rect, "Capture")){
                var _snapshot = new AnimationSnapshot(propertyBinder.gameObject, _captureOption);
                AnimationClip clip = null;
                _snapshot.CapturePoseA();   
                clip = _snapshot.CreateAnimationClipA($"Off_{propertyBinder.gameObject.name}_{Mathf.Abs(propertyBinder.GetInstanceID())}_AutoGenerated");
                if(offAnimationProp.objectReferenceValue is AnimationClip oldClip && oldClip.name.EndsWith("_AutoGenerated")){
                    AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(oldClip));
                    AssetDatabase.SaveAssets();
                    offAnimationProp.objectReferenceValue = null;
                }
                offAnimationProp.objectReferenceValue = clip;
            }

            var (leftRect, rightRect) = EditorGUILayout.GetControlRect().SliceVerticalRatio(0.5f);
            if(GUI.Button(leftRect, "Preview On")){
                if(onAnimationProp.objectReferenceValue is AnimationClip clip){
                    clip.SampleAnimation(propertyBinder.gameObject, 0);
                }
            }
            if(GUI.Button(rightRect, "Preview Off")){
                if(offAnimationProp.objectReferenceValue is AnimationClip clip){
                    clip.SampleAnimation(propertyBinder.gameObject, 0);
                }
            }

            serializedObject.ApplyModifiedProperties();
        }
    }
}
