using System;
using System.Collections.Generic;
using System.Linq;

using HUtil.UI;
using HUtil.Runtime.Extension;
using HUtil.UI.Binder;

using UnityEditor;
using UnityEngine;
using HUtil.Editor;
using HUtil.Editor.Animation;

namespace HUtil.UI.Editor
{
    [CustomEditor(typeof(PropertyBinder))]
    public class PropertyBinderDrawer : UnityEditor.Editor
    {
        private AnimationSnapshot _snapshotA;
        private AnimationSnapshot _snapshotB;

        public override void OnInspectorGUI(){
            serializedObject.Update();

            var propertyBinder = target as PropertyBinder;

            var targetProp = serializedObject.FindProperty("_target");
            var onAnimationProp = serializedObject.FindProperty("_onAnimation");
            var offAnimationProp = serializedObject.FindProperty("_offAnimation");
            var boolPropProp = serializedObject.FindProperty("_isOn_prop");

            // # Target
            EditorGUILayout.PropertyField(targetProp, new GUIContent("Target"));

            // # Is On Property
            EditorGUILayout.PropertyField(boolPropProp, new GUIContent("Is On Property"));

            // # On Animation
            EditorGUILayout.PropertyField(onAnimationProp, new GUIContent("On Animation"));
            var rect = EditorGUILayout.GetControlRect();
            if(_snapshotA == null && GUI.Button(rect, "Start Record")){
                _snapshotA = new AnimationSnapshot(propertyBinder.gameObject);
                _snapshotA.CapturePoseA();
            }
            GUI.backgroundColor = Color.red;
            if(_snapshotA != null && GUI.Button(rect, "End Record")){
                _snapshotA.CapturePoseB();
                var clip = _snapshotA.CreateAnimationClipAB($"On_{propertyBinder.gameObject.name}_{Mathf.Abs(propertyBinder.GetInstanceID())}_AutoGenerated");
                if(onAnimationProp.objectReferenceValue is AnimationClip oldClip && oldClip.name.EndsWith("_AutoGenerated")){
                    AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(oldClip));
                    AssetDatabase.SaveAssets();
                    onAnimationProp.objectReferenceValue = null;
                }
                onAnimationProp.objectReferenceValue = clip;
                _snapshotA = null;
            }
            GUI.backgroundColor = Color.white;

            // # Off Animation
            EditorGUILayout.PropertyField(offAnimationProp, new GUIContent("Off Animation"));
            rect = EditorGUILayout.GetControlRect();
            if(_snapshotB == null && GUI.Button(rect, "Start Record")){
                _snapshotB = new AnimationSnapshot(propertyBinder.gameObject);
                _snapshotB.CapturePoseA();
            }
            GUI.backgroundColor = Color.red;
            if(_snapshotB != null && GUI.Button(rect, "End Record")){
                _snapshotB.CapturePoseB();
                var clip = _snapshotB.CreateAnimationClipAB($"Off_{propertyBinder.gameObject.name}_{Mathf.Abs(propertyBinder.GetInstanceID())}_AutoGenerated");
                if(offAnimationProp.objectReferenceValue is AnimationClip oldClip && oldClip.name.EndsWith("_AutoGenerated")){
                    AssetDatabase.DeleteAsset(AssetDatabase.GetAssetPath(oldClip));
                    AssetDatabase.SaveAssets();
                    offAnimationProp.objectReferenceValue = null;
                }
                offAnimationProp.objectReferenceValue = clip;
                _snapshotB = null;
            }
            GUI.backgroundColor = Color.white;

            var (leftRect, rightRect) = EditorGUILayout.GetControlRect().SliceVerticalRatio(0.5f);
            if(GUI.Button(leftRect, "Preview On")){
                if(onAnimationProp.objectReferenceValue is AnimationClip clip){
                    clip.SampleAnimation(propertyBinder.gameObject, 0);
                }
            }
            if(GUI.Button(rightRect, "Preview Off")){
                if(offAnimationProp.objectReferenceValue is AnimationClip clip){
                    clip.SampleAnimation(propertyBinder.gameObject, 0);
                }
            }

            serializedObject.ApplyModifiedProperties();
        }
    }
}
